services:
  financio-db:
    image: postgres:16-alpine
    container_name: financio-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: financio
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapp:
    build:
      context: .
      dockerfile: ./dockerfiles/webapp/Dockerfile
      network: host
    container_name: financio-webapp
    ports:
      - 8013:8000

    volumes:
      - ./financio_suite:/financio
      - ./.env:/.env
    environment:
      - DEBUG=True
      - DB_HOST=financio-db
      - DB_PORT=5432
      - DB_NAME=financio
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=financio_suite.settings
      - PYTHONPATH=/financio
    env_file:
      - .env
    depends_on:
      - financio-db
    command:
      - sh
      - -c
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000

  unit_tests:
    image: financio-webapp:latest
    container_name: financio-unit_tests
    volumes:
      - ./financio_suite:/financio
      - ./tests:/financio/tests
      - ./.env:/.env
    environment:
      - DEBUG=True
      - DB_HOST=financio-db
      - DB_PORT=5432
      - DB_NAME=financio
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=financio_suite.settings
      - PYTHONPATH=/financio
    env_file:
      - .env
    working_dir: /financio/tests
    tty: true
    command: ["tail", "-f", "/dev/null"]
