services:
  financio-db:
    image: postgres:16-alpine
    container_name: financio-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: financio
    volumes:
      - ./db/data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 400M

  webapp:
    build:
      context: .
      dockerfile: ./dockerfiles/webapp/Dockerfile
    container_name: financio-webapp
    ports:
      - "8013:8000"
    volumes:
      - ./financio_suite:/financio
    environment:
      - DEBUG=False
      - DB_HOST=financio-db
      - DB_PORT=5432
      - DB_NAME=financio
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - financio-db
    deploy:
      resources:
        limits:
          memory: 450M
    command: >
      sh -c "
      python3 manage.py migrate &&
      python3 manage.py collectstatic --noinput &&
      gunicorn financio_suite.wsgi:application
      --bind 0.0.0.0:8000
      --workers 1
      --threads 2
      --timeout 120
      "

  nginx:
    image: nginx:alpine
    container_name: financio-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - webapp

  certbot:
    image: certbot/certbot
    container_name: financio-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot